[package]
name = "webdav-handler"

# When releasing to crates.io:
# - Update html_root_url in src/lib.rs
# - Update CHANGELOG.md.
# - Run ./generate-readme
# - Create git tag v0.x.y
version = "0.2.0-alpha.2"

readme = "README.md"
description = "handler for the HTTP and Webdav protocols with filesystem backend"
documentation = "https://docs.rs/webdav-handler"
repository = "https://github.com/miquels/webdav-handler-rs"
homepage = "https://github.com/miquels/webdav-handler-rs"
authors = ["Miquel van Smoorenburg <mike@langeraar.net>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["webdav"]
categories = ["web-programming"]

[lib]
name = "webdav_handler"
path = "src/lib.rs"

[dependencies]
bytes = "0.4.12"
headers = "0.2.1"
htmlescape = "0.3.1"
http = "0.1.17"
lazy_static = "1.3.0"
libc = "0.2.58"
log = "0.4.6"
lru = "0.1.15"
mime_guess = "1.8.7"
parking_lot = "0.8.0"
percent-encoding = "1.0.1"
pin-project = "0.4"
regex = "1.1.7"
serde = "1.0.93"
serde_derive = "1.0.93"
time = "0.1.42"
url = "1.7.2"
uuid = { version = "0.7.4", features = ["v4"] }
xml-rs = "0.8.0"
xmltree = "0.8.0"

futures = { package = "futures-preview", version = "=0.3.0-alpha.19", features = ["io-compat"] }
http-body = "=0.2.0-alpha.3"
pin-utils = "0.1.0-alpha.4"
tokio-executor = "=0.2.0-alpha.6"

[dev-dependencies]
#actix = "0.7.9"
#actix-web = "0.7.19"
#tokio-current-thread = "0.1.6"
clap = "2.33.0"
env_logger = "0.6.1"
failure = "0.1.5"
hyper = "=0.13.0-alpha.4"
tokio = "=0.2.0-alpha.6"

